spring:
  application:
    name: moli-client-demo


moli:
  client:
    accessKey: ak_moli_3b486211859274d4f8dca78a3b02ef1f
    secretKey: sk_moli_2-CK6oUL_ZJz8CkFLDd83Q
    gatewayHost: http://localhost:8090
server:
  port: 8092
