spring:
  application:
    name: moli-api-interface

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moliapi_interface?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 1314

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /static/**  # 限制静态资源路径，避免与 API 冲突

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 8091
  servlet:
    context-path: /
