
server:
  port: 8090
spring:
  application:
    name: moli-api-gateway
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    gateway:
      routes:
        - id: moli-api-backend
          uri: http://localhost:8101
          predicates:
            - Path=/api/**
    nacos:
      discovery:
        server-addr: 127.0.0.1:8849

dubbo:
  application:
    name: moli-api-gateway

  registry:
    address: nacos://127.0.0.1:8849

  protocol:
    name: dubbo
    port: -1   # ????

logging:
  level:
    root: INFO
    com.bingli: DEBUG
    org.springframework: WARN
    com.alibaba.nacos: DEBUG
    org.apache.dubbo: DEBUG
